package lt.bit.products.ui.service.error;

public enum ErrorCode {
  VALUE_TOO_SHORT, EMPTY_VALUE, NEGATIVE_NUMBER, PRODUCT_NOT_FOUND, INVALID_FILE_TYPE, FILE_TOO_LARGE, NOT_SAME_PASSWORDS,
  USER_NOT_FOUND, PASSWORD_IS_REQUIRED, MANDATORY_FIELDS
}
